services:
  - type: web
    name: saphir-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_entry.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: TURSO_URL
        value: "libsql://saphir-pro-miessou1978.aws-ap-northeast-1.turso.io"
      - key: TURSO_TOKEN
        value: "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJqa0RNREdfTkVmR3RNdzZqcHNWb2V3Iiwib3JnX2lkIjoxMDAwMTg2NjIxfQ.IEcXzHaAO2FcA4G-0L3TOxG5OCmbFkOxHfAaZ6SrZ676_X-4bP4FSsgWp5BfWMuIszqZVQV5vg1k2wtj_npWDQ"
      - key: STUDENT_PASSWORD
        value: "RECEPTIOn8@2025"
      - key: APP_PASSWORD
        value: "RECEPTIOn8@2024"
